### PR TITLE
Ec with ve

### LINKED ISSUE #8: The program is aborted when the Ec is large
stop at t=0.55 when Ec=400，maxlevel=11
and stop at t=0.008 when  Ec=400，maxlevel=12
issue

### PR DESCRIPTION
**Pull request by VatsalSy**
@spilltheT  please test v4.0 with a large value of Ec... you must assign De be a large number (I would do 1e1*\sqrt{Ec} or so)..  As long as the system reaches a equilibrium state before t = De/\sqrt{Ec}, the code will work.. 

v3.0 also works but it is very slow.. we would need a very high refinement here

v2.1 also works fine (-ish)... but the interface is not very stable. it is not a deal breaker but hopefully v4.0 is general enough that we won't have to worry about this.. 

Please test and review the codes asap so that @alpha1958627 can use it to run some large Ec cases. 

This PR should fix https://github.com/Computational-Multiphase-Physics/SoftSliding/issues/8

### CODE REVIEW

**Review by spilltheT — COMMENTED** [review]
Works fine for large Ec

**Comment by VatsalSy** [comment]
@ayushkumardixit  please check the elastic normalization parts! Thanks.

**Comment by ayushkumardixit** [comment]
The parts on normalization seem correct. 
rho, G, and R_0 are used which gives the timescale: \sqrt{\rho R_0^2/G} (Inertio-elastic time scale perhaps) prompting changes in the values we put. I checked each term and all seems correct.

**Comment by ayushkumardixit** [comment]
@spilltheT Just a small caution for Jnan (also tell this to Jiahua to avoid any future confusion): Even though the process time scale is now inertioelastic time, in v4, De is still defined as lambda over inertiocapillary time (\sqrt{\rhoR_0^3/\gamma}).

**Review by ayushkumardixit — APPROVED** [review]

**Comment by VatsalSy** [comment]
thanks @ayushkumardixit

**Pull request merged**
